#!/bin/bash

set -e

. ~/.bashrc

# options: debug info notice warn error crit alert emerg
: ${NGINX_LOG_LEVEL:=info}

# options: on off
: ${NGINX_ACCESS_LOG:=on}


echo "Rewriting configuration based on environment ..."
if [ "$ENVIRONMENT" == "local" ]; then
    echo "Local environment: generating self signed certs ..."
    mkdir -p /etc/ssl/certs
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout /etc/ssl/certs/local-key.pem \
        -out /etc/ssl/certs/local-cert.pem \
        -subj '/C=US/ST=New York/L=New York/O=Valuphone/OU=Ops/CN=docker.local/
        emailAddress=nobody@docker.local/
        subjectAltName=DNS.1=my.docker.local,
        DNS.2=kzui.docker.local,
        DNS.3=api.valuphone.com
        DNS.4=docker.local'

    sed -ir '/ssl_certificate /s/secrets\/tls\/chain/ssl\/certs\/local-cert.pem/' \
        /etc/nginx/nginx.conf
    sed -ir '/ssl_certificate_key/s/secrets\/tls\/key/ssl\/certs\/local-key.pem/' \
        /etc/nginx/nginx.conf
    sed -ir '/ssl_trusted_certificate/d' /etc/nginx/nginx.conf
fi


echo "Rewriting debug_log to: $NGINX_LOG_LEVEL ..."
sed -ir "/error_log/s/warn/$NGINX_LOG_LEVEL/" /etc/nginx/nginx.conf


if [ "$NGINX_ACCESS_LOG" == "off" ]; then
    echo "Setting access_log to: $NGINX_ACCESS_LOG ..."
    sed -ir '/access_log/s/\/dev\/stdout     main/                off/' \
        /etc/nginx/nginx.conf
fi

cat /etc/nginx/nginx.conf


echo "Ensuring permissions ..."
chown -R nginx:nginx /etc/nginx/nginx.conf


echo "Starting nginx ..."
cd ~
    exec nginx -g 'daemon off;' 2>&1