apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webproxy
spec:
  replicas: 1
  template:
    metadata:
      name: webproxy
      labels:
        app: webproxy
        project: valuphone
        environment: production
    spec:
      minReadySeconds: 60
      volumes:
        - name: tls
          secret:
            secretName: webproxy-tls
      containers:
        - name: webproxy
          image: callforamerica/webproxy
          env:
            - name: NGINX_LOG_LEVEL
              value: info          
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
            - name: https
              protocol: TCP
              containerPort: 443
            - name: crossbar-tls
              protocol: TCP
              containerPort: 8443
          volumeMounts:
            - name: tls
              readOnly: true
              mountPath: /etc/secrets/tls
          resources:
            requests:
              cpu: 1
              memory: 1G
            limits:
              cpu: 1
              memory: 1G 
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 45
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 45
            timeoutSeconds: 15
          imagePullPolicy: Always
      restartPolicy: Always
