kind: Pod
apiVersion: v1
metadata:
  name: webproxy
  labels:
    app: webproxy
    project: valuphone
    role: reverse-proxy
spec:
  volumes:
    - name: combo-tls
      secret:
        secretName: combo-tls
  containers:
    - name: webproxy
      image: callforamerica/webproxy
      imagePullPolicy: Always
      ports:
        - name: http
          protocol: TCP
          containerPort: 80
        - name: https
          protocol: TCP
          containerPort: 443
        - name: crossbar-tls
          protocol: TCP
          containerPort: 8443
      # args: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - name: combo-tls
          readOnly: true
          mountPath: /etc/secrets/tls
      resources:
        requests:
          cpu: 1
          memory: 1G
        limits:
          cpu: 1
          memory: 1G 
      # readinessProbe:
      #   httpGet:
      #     path: /
      #     port: 80
      #   initialDelaySeconds: 15
      #   timeoutSeconds: 3
      # livenessProbe:
      #   httpGet:
      #     path: /
      #     port: 80
      #   initialDelaySeconds: 15
      #   timeoutSeconds: 3
  restartPolicy: Always
