kind: Service
apiVersion: v1
metadata: 
  name: webproxy
  labels:
    app: webproxy
    project: valuphone
    role: reverse-proxy
spec:
  selector:
    app: webproxy
    project: valuphone
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 80
    - name: https
      protocol: TCP
      port: 443
      nodePort: 443