kind: Pod
apiVersion: v1
metadata:
  name: webproxy
  labels:
    app: webproxy
    project: valuphone
    role: reverse-proxy
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: Always
      ports:
        - name: http
          protocol: TCP
          containerPort: 80
        - name: https
          protocol: TCP
          containerPort: 443
      # resources:
      #   requests:
      #     cpu: 2
      #     memory: 1G
      #   limits:
      #     cpu: 2
      #     memory: 1G 
      # readinessProbe:
      #   httpGet:
      #     path: /monster-ui
      #     port: 80
      #   initialDelaySeconds: 15
      #   timeoutSeconds: 3
      # livenessProbe:
      #   httpGet:
      #     path: /monster-ui
      #     port: 80
      #   initialDelaySeconds: 15
      #   timeoutSeconds: 3
  restartPolicy: Always
