kind: Service
apiVersion: v1
metadata: 
  name: webproxy
  labels:
    app: webproxy
    project: valuphone
    role: reverse-proxy
spec:
  selector:
    app: webproxy
    project: valuphone
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 81
    - name: https
      protocol: TCP
      port: 443
      nodePort: 444
    - name: crossbar-tls
      protocol: TCP
      port: 8443
      nodePort: 8443